services:
  spark-iceberg:
    build: .
    ports:
      - "4040:4040"
      - "18080:18080" # Spark History Server
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - ICEBERG_CATALOG=news_catalog
      - ICEBERG_WHEREHOUSE=file:///data/iceberg
    volumes:
      - ./data/iceberg:/data/iceberg
      - ./logs:/apps/logs
    depends_on:
      - spark-master
      - cassandra
      - kafka
  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
  spark-worker:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_LOCAL_IP=spark-worker
    depends_on:
      - spark-master

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=NewsCluster
      - CASSANDRA_DC=datacenter1
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.6
    ports:
      - "2181:2181"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

volumes:
  iceberg-data:
  minio-data: