storage:
  hdfs:
    host: localhost
    port: 9000
    user: hadoop
    base_path: /data/news
    formats:
      - cold: "parquet"
      - archive: "avro"
    compresison: "snappy"
    replication: 3

  hbase:
    host: localhost
    port: 9090
    table: news
    column_family: cf
    max-versions: 3
    block_cache: true
    bloom_filter: true

  retention:
    hot_data_days: 7
    warm_data_days: 30
    cold_data_days: 365
  
  processing:
    batch_size: 1000
    max_workers: 4
    timeout: 30
  
logging:
  level: INFO
kafka:
  bootstrap_servers: "192.168.100.2:9092"
  topics:
    - "raw-news"
    - "processed-news"
  group_id: "news_storage_consumer"
  
monitoring:
  prometheus_port: 8000
  log_level: INFO